// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj0izG5DKkvHfFkIfF8KzbFBymtU_no-E',
    appId: '1:969379902196:web:1bbc469d6e859f0585a4a1',
    messagingSenderId: '969379902196',
    projectId: 'chatapp-d8c4c',
    authDomain: 'chatapp-d8c4c.firebaseapp.com',
    storageBucket: 'chatapp-d8c4c.appspot.com',
    measurementId: 'G-BX500FWQFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPaojFEDxMvPcfk-lMmg_k4yvxQu8vcd4',
    appId: '1:969379902196:android:12697872f9ee191e85a4a1',
    messagingSenderId: '969379902196',
    projectId: 'chatapp-d8c4c',
    storageBucket: 'chatapp-d8c4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKuNa1TYl1BI80dtU6Cvvdi4X6vbSkLps',
    appId: '1:969379902196:ios:e96d309b0151839585a4a1',
    messagingSenderId: '969379902196',
    projectId: 'chatapp-d8c4c',
    storageBucket: 'chatapp-d8c4c.appspot.com',
    iosBundleId: 'com.example.juanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKuNa1TYl1BI80dtU6Cvvdi4X6vbSkLps',
    appId: '1:969379902196:ios:2be9b61dddb0296885a4a1',
    messagingSenderId: '969379902196',
    projectId: 'chatapp-d8c4c',
    storageBucket: 'chatapp-d8c4c.appspot.com',
    iosBundleId: 'com.example.juanapp.RunnerTests',
  );
}
